### ISSUE TITLE
建议适配番剧转换

### ISSUE THREAD

**Issue by Zzy-114514** [SimoLin/bilibili_video_converter#1]
找了很多资源，但似乎只有这一个可以在我的电脑上运行，并且我还发现编译后可以在winlator上直接运行。
原本的代码只能识别`title`和`owner_name`，但番剧的intro中没有`owner_name`，且番剧命名为`title-index-name`更合理。
希望作者能改一下并用相同的编译器再编译一下。

**Comment by SimoLin** [comment]
抱歉，一直没看到你的Issue，现在已更新v1.0.1版本，可以试试

- 现在可以正确视频普通视频、分片视频合集、番剧等类型
- 现在导出后会等待 10S 再开始重命名视频文件为中文，同时会分文件夹存放
  - 普通视频、分片视频合集 文件夹以 UP主 为名称，文件命名格式为 Title视频名称_分片Index_分片名称IndexTitle.mp4
  - 番剧 以 番剧标题 为名称，文件命名格式为 分片Index_分片名称IndexTitle.mp4

**Comment by SimoLin** [comment]
> 找了很多资源，但似乎只有这一个可以在我的电脑上运行，并且我还发现编译后可以在winlator上直接运行。 原本的代码只能识别`title`和`owner_name`，但番剧的intro中没有`owner_name`，且番剧命名为`title-index-name`更合理。 希望作者能改一下并用相同的编译器再编译一下。

抱歉，一直没看到你的Issue，现在已更新v1.0.1版本，可以试试

- 现在可以正确识别普通视频、分片视频合集、番剧等类型
- 现在导出后会等待 10S 再开始重命名视频文件为中文，同时会分文件夹存放
  - 普通视频、分片视频合集 文件夹以 UP主 为名称，文件命名格式为 Title视频名称_分片Index_分片名称IndexTitle.mp4
  - 番剧 以 番剧标题 为名称，文件命名格式为 分片Index_分片名称IndexTitle.mp4
